import { createContext, useContext, useEffect, useMemo, useState, useCallback } from 'react';

const translations = {
  en: {
    direction: 'ltr',
    nav: {
      brand: 'CarePulse',
      panel: 'Panel',
      hello: 'Hello',
      profile: 'Profile',
      logout: 'Logout',
      changeLanguage: 'العربية',
      languageLabel: 'Language',
    },
    common: {
      loading: 'Loading CarePulse...',
      unknown: 'Unknown',
      yes: 'Yes',
      no: 'No',
      cancel: 'Cancel',
      save: 'Save',
      close: 'Close',
      na: 'N/A',
      anonymous: 'Anonymous',
      today: 'Today',
    },
    login: {
      title: 'Welcome Back',
      subtitle: 'Please enter your medical portal credentials',
      email: 'Email Address',
      password: 'Password',
      signIn: 'Sign In',
      noAccount: "Don't have an account?",
      createAccount: 'Create Portal Account',
      portalTitle: 'CarePulse Portal',
      medicalPortal: 'Medical Portal',
      empowering: 'Empowering healthcare teams and patient coordination through advanced real-time medical insights.',
      or: 'or',
      patient: 'Patient',
      doctor: 'Doctor',
      googleFailed: 'Google login failed',
      toast: {
        invalidEmail: 'Please enter a valid email address.',
        invalidPassword: 'Password must be at least 6 characters.',
        success: 'Signed in successfully',
        invalidCredentials: 'Invalid email or password!',
        failed: 'Failed to log in. Please try again.',
      },
    },
    register: {
      title: 'Create Account',
      subtitle: 'Get started by filling your registration info',
      fullName: 'Full Name',
      email: 'Email Address',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      roleLabel: 'Portal Access Role',
      patient: 'Patient',
      doctor: 'Doctor',
      signUp: 'Sign Up',
      existingAccount: 'Already have an account?',
      signIn: 'Sign In',
      toast: {
        invalidName: 'Please enter a valid full name (at least 3 characters).',
        invalidEmail: 'Please enter a valid email address.',
        invalidPassword: 'Password must be at least 6 characters long.',
        passwordMismatch: 'Passwords do not match!',
        emailInUse: 'This email is already in use!',
        successTitle: 'Welcome to CarePulse!',
        successText: 'Your account has been created successfully.',
        failed: 'Registration failed. Try again.',
      },
    },
    landing: {
      badge: 'Trusted medical booking portal',
      headline: 'CarePulse',
      subtitle:
        'Book appointments, view doctor details, manage prescriptions, and pay visit fees from one clean healthcare workspace.',
      makeAppointment: 'Make An Appointment',
      createAccount: 'Create Account',
      statsTitle: 'Today at CarePulse',
      stats: {
        doctors: 'Doctors',
        specialties: 'Specialties',
        patientVisits: 'Patient visits',
      },
      features: {
        findDoctor: {
          title: 'Find the right doctor',
          text: 'Browse specialties, doctor profiles, clinic notes, and available appointment slots.',
        },
        bookFast: {
          title: 'Book in minutes',
          text: 'Choose a day and time, then track request status from your patient dashboard.',
        },
        payments: {
          title: 'Simple payments',
          text: 'Patients can pay appointment fees from their booking history.',
        },
      },
      footer: {
        text: 'CarePulse keeps patients, doctors, and appointments connected in one reliable medical portal.',
        copyright: '© 2026 CarePulse. All rights reserved.',
      },
    },
    profile: {
      title: 'My Profile Settings',
      accountType: 'Account Type',
      specialty: 'Medical Specialty',
      bio: 'Professional Bio',
      saveProfile: 'Save Profile',
      savingChanges: 'Saving Changes...',
      emailHelp: 'Email account cannot be changed',
      nameRequired: 'Name field cannot be empty!',
      updated: 'Profile Updated!',
      updatedText: 'Your personal settings have been saved successfully.',
      failedLoad: 'Failed to load profile data.',
      failedSave: 'Failed to update profile.',
      back: 'Back',
      adminSettings: 'Admin Settings',
      editProfile: 'Edit Profile',
      username: 'Username',
      emailLabel: 'Email',
      firstName: 'First Name',
      lastName: 'Last Name',
      male: 'Male',
      female: 'Female',
      bloodType: 'Blood Type',
      address: 'Address',
      fee: 'Fee',
      clinicAddress: 'Clinic Address',
      saving: 'Saving...',
      saveChanges: 'Save Changes',
      profileUpdated: 'Profile updated successfully!',
      profileFailed: 'Failed to update profile.',
      changePicture: 'Change Profile Picture',
      uploading: 'Uploading...',
      pictureUploaded: 'Profile picture updated!',
      pictureFailed: 'Failed to upload picture.',
      pictureTooLarge: 'Image must be under 5MB.',
    },
    admin: {
      title: 'Admin Control Center',
      dashboard: 'Admin Control Center',
      tabs: ['Users', 'Doctors', 'Specialties', 'Appointments', 'Analytics'],
      doctorsManagement: 'Doctors Management',
      usersOverview: 'All Users',
      specialtiesManagement: 'Specialties Management',
      appointmentsOverview: 'Appointments Overview',
      configManagement: 'System Configuration',
      analytics: 'System Analytics',
      addSpecialty: 'Add Specialty',
      saveSpecialty: 'Save Specialty',
      specialtyName: 'Specialty',
      specialtyDescription: 'Description',
      noSpecialties: 'No specialties configured yet.',
      saveConfig: 'Save Config',
      addConfig: 'Add Config',
      noConfigs: 'No system configuration entries yet.',
      refresh: 'Refresh',
      refreshing: 'Refreshing...',
      noAppointments: 'No appointments found.',
      noUsers: 'No doctors or patients available.',
      noDoctors: 'No doctor records found.',
      noDetails: '—',
      deleteSpecialtyConfirm: 'Delete specialty?',
      deleteSpecialtyText: 'This action cannot be undone.',
      deleteConfigConfirm: 'Delete configuration?',
      deleteConfigText: '',
      deleted: 'Deleted',
      created: 'Created',
      updated: 'Updated',
      unable: 'Unable to',
      specialtyNameRequired: 'Specialty name is required.',
      configKeyValueRequired: 'Config key and value are required.',
      doctorUpdateFailed: 'Failed to update doctor',
      userStatusChangeFailed: 'Unable to change status',
      specialtyAddFailed: 'Unable to add specialty',
      specialtyUpdateFailed: 'Could not update specialty',
      specialtyDeleteFailed: 'Unable to delete specialty',
      configSaveFailed: 'Unable to save config',
      configUpdateFailed: 'Unable to update config',
      configDeleteFailed: 'Unable to delete config',
      panel: {
        overviewCards: {
          users: 'Users',
          doctors: 'Doctors',
          pendingApprovals: 'Pending Approvals',
          appointments: 'Appointments',
        },
        usersPanel: {
          title: 'All Registered Users',
          name: 'Name',
          email: 'Email',
          role: 'Role',
          status: 'Status',
          actions: 'Actions',
          approve: 'Approve',
          block: 'Block',
          rowsPerPage: 'Rows per page',
          prev: 'Prev',
          next: 'Next',
        },
        doctorsPanel: {
          noDoctors: 'No doctors found.',
          approved: 'Approved',
          pending: 'Pending',
          generalPractitioner: 'General Practitioner',
          noAddress: 'Clinic address not listed',
          bookAppointment: 'Book Appointment',
          approveActivate: 'Approve & Activate Doctor',
          showing: 'Showing',
          to: 'to',
          of: 'of',
          doctors: 'doctors',
          prev: 'Prev',
          next: 'Next',
        },
        specialtiesPanel: {
          title: 'Medical Specialties Management',
          name: 'Specialty Name',
          save: 'Save Specialty',
          add: 'Add Specialty',
          cancel: 'Cancel',
          noSpecialties: 'No specialties configured yet.',
          edit: 'Edit Specialty',
          delete: 'Delete Specialty',
        },
        appointmentsPanel: {
          title: 'Appointments Overview Log',
          refreshLogs: 'Refresh Logs',
          refreshing: 'Refreshing...',
          patient: 'Patient',
          doctor: 'Doctor',
          dateSlot: 'Date / Slot',
          status: 'Status',
          payment: 'Payment',
          notes: 'Notes',
          noAppointments: 'No appointments found.',
          unknown: 'Unknown',
          rowsPerPage: 'Rows per page',
          prev: 'Prev',
          next: 'Next',
          paid: 'Paid',
          unpaid: 'Unpaid',
        },
        analyticsPanel: {
          title: 'System Analytics Engine',
          appointmentChart: 'Appointment Status Chart',
          userChart: 'User Status Distribution',
          specialtyChart: 'Doctors by Specialty Summary',
          noSpecialtyData: 'No specialty data available.',
        },
        configPanel: {
          title: 'System Settings Configuration',
          configKey: 'Config Key',
          configValue: 'Config Value',
          save: 'Save Config',
          add: 'Add Config',
          cancel: 'Cancel',
          noConfigs: 'No system configuration entries yet.',
        },
      },
    },
    doctor: {
      title: 'Doctor Workspace',
      tabs: ['Patient Appointments', 'Manage Work Schedule', 'Patients Medical History'],
      currentBookings: 'Current & Pending Bookings',
      patientName: 'Patient Name',
      dayTime: 'Day & Time',
      status: 'Status',
      actions: 'Actions',
      noAppointments: 'No active appointments found.',
      approve: 'Approve',
      cancel: 'Cancel',
      completePrescribe: 'Complete & Prescribe',
      visitCompleted: 'Visit Completed!',
      recordUpdated: 'Patient record updated.',
      fillFields: 'Please fill in both fields.',
      failedSaveRecord: 'Failed to save record.',
      manageShift: 'Setup Working Shift',
      selectDay: 'Select Day',
      totalHours: 'Total Work Hours',
      slotDuration: 'Slot Duration',
      generateSlots: 'Generate Shift Slots',
      noSlots: 'No slots active on your schedule yet.',
      weeklySchedule: 'Your Weekly Schedule (Grouped by Day)',
      recordsHistory: 'Patients Medical Records History',
      searchPatient: 'Search Patient Name...',
      noMatchingRecords: 'No matching records found in patient history.',
      medicalRecord: 'Patient Medical Record',
      diagnosis: 'Diagnosis',
      prescriptionNotes: 'Prescription & Notes',
      saveComplete: 'Save & Complete Visit',
      closeRecord: 'Close Record',
      archivedPrescription: 'Archived Prescription',
      prescription: 'Prescription',
      dateOfVisit: 'Date of Visit',
      noDoctorRecords: 'No working days scheduled yet.',
      chooseDay: '1. Choose Day:',
      availableTimes: '2. Available Times:',
      selectDayToView: 'Select a day to view slots.',
      bookingConfirmationTitle: 'Confirm Booking',
      bookingConfirmationText: 'Book with Dr. {doctor} on {day} [{time}]?',
      confirmBookBtn: 'Yes, Book it!',
      cancelBookBtn: 'Cancel',
      bookSuccess: 'Appointment secured successfully.',
      bookingFailed: 'Booking failed.',
      doctorName: 'Doctor Name',
    },
    patient: {
      title: 'Patient Center',
      subtitle: 'Stay healthy! 🛡️',
      tabs: ['Book An Appointment', 'My Bookings & Records'],
      availableDoctors: 'Available Doctors & Specialists',
      noDoctors: 'No registered doctors available right now.',
      chooseDay: 'Choose Day:',
      availableTimes: 'Available Times:',
      selectDay: 'Select a day to view slots.',
      bookAppointment: 'Book An Appointment',
      yourHistory: 'Your Booking History',
      doctorName: 'Doctor Name',
      medicalPrescription: 'Medical Prescription',
      appointmentAvailableAfter: 'Available after visit',
      appointmentBooked: 'Booked!',
      close: 'Close',
      officialPrescription: 'Official Medical Prescription 🩺',
      diagnosisLabel: 'Diagnosis (التشخيص):',
      prescriptionLabel: 'Prescription & Notes (العلاج والتعليمات):',
      searchPlaceholder: 'Search doctor name...',
      specialtyFilter: 'Filter by Specialty',
      allSpecialties: 'All Specialties',
      specialist: 'Specialist',
    },
    appointmentDetail: {
      title: 'Appointment Details',
      patient: 'Patient',
      doctor: 'Doctor',
      dayTime: 'Day / Time',
      status: 'Status',
      loading: 'Loading...',
      notFound: 'No appointment found.',
      approve: 'Approve',
      rejectCancel: 'Reject / Cancel',
      cancelAppointment: 'Cancel Appointment',
      completeVisit: 'Complete Visit',
      diagnosis: 'Diagnosis',
      prescription: 'Prescription',
      saveComplete: 'Save & Complete',
      fillDiagnosisPrescription: 'Please fill diagnosis and prescription',
      approved: 'Approved',
      cancelled: 'Cancelled',
      completed: 'Completed',
      failed: 'Failed',
      notificationApprovedTitle: 'Appointment approved',
      notificationApprovedBody: 'Your appointment was approved.',
      notificationCancelledTitle: 'Appointment cancelled',
      notificationCancelledBody: 'Your appointment was cancelled.',
      notificationCompletedTitle: 'Visit completed',
      notificationCompletedBody: 'Your visit was completed and prescription is available.',
    },
    overviewCards: {
      users: 'Users',
      doctors: 'Doctors',
      pendingApprovals: 'Pending Approvals',
      appointments: 'Appointments',
    },
    statuses: {
      approved: 'Approved',
      pending: 'Pending',
      blocked: 'Blocked',
      cancelled: 'Cancelled',
      completed: 'Completed',
      unknown: 'Unknown',
    },
    roles: {
      doctor: 'Doctor',
      patient: 'Patient',
      admin: 'Admin',
      unknown: 'Unknown',
    },
    days: {
      Monday: 'Monday',
      Tuesday: 'Tuesday',
      Wednesday: 'Wednesday',
      Thursday: 'Thursday',
      Friday: 'Friday',
      Saturday: 'Saturday',
      Sunday: 'Sunday',
    },
    notifications: {
      newRequestTitle: 'New appointment request',
      newRequestBody: 'Patient {patient} requested {day} {time}',
      bookingCreatedTitle: 'Booking created',
      bookingCreatedBody: 'Your booking with Dr. {doctor} on {day} {time} is pending.',
      bookedTitle: 'Booked!',
      bookedSuccess: 'Appointment secured successfully.',
      bookingFailed: 'Booking failed.',
      title: 'Notifications',
      noNotifications: 'No notifications yet.',
      unread: 'unread',
      deleteConfirm: 'Delete notification?',
      delete: 'Delete',
      deleted: 'Deleted',
      failedDelete: 'Failed to delete',
      open: 'Open',
      markAsRead: 'Mark as read',
    },
    home: {
      welcome: 'Welcome',
      manageDoctor: 'Manage your schedule, patient requests and reviews from one place.',
      findCare: 'Find care, book appointments and message your providers quickly.',
      overviewSystem: 'Overview system health and pending tasks.',
      openDashboard: 'Open Dashboard',
      viewNotifications: 'View Notifications',
      keyFeatures: 'Key Features',
      easyBooking: 'Easy Booking',
      easyBookingDesc: 'Schedule appointments in a few clicks and get reminders.',
      trustedCare: 'Trusted Care',
      trustedCareDesc: 'Verified professionals and secure medical records.',
      fastMessaging: 'Fast Messaging',
      fastMessagingDesc: 'Direct secure messaging with your care team.',
      whatPeopleSay: 'What people say',
      profile: 'Profile',
      appointments: 'Appointments',
      recentNotifications: 'Recent Notifications',
      noRecentNotifications: 'No recent notifications.',
      new: 'New',
      quickLinks: 'Quick Links',
      myVisits: 'My Visits',
      allNotifications: 'All Notifications',
      support: 'Support',
    },
    verify: {
      title: 'Verify Account',
      enterCode: 'Enter the code sent to',
      yourEmail: 'your email',
      code: 'Verification Code',
      activating: 'Verifying...',
      activateAccount: 'Activate Account',
      invalidInput: 'Invalid Input',
      enterCodeMessage: 'Please enter the 6-digit code.',
      success: 'Verified!',
      failed: 'Verification Failed',
      incorrectCode: 'The code is incorrect or has expired.',
    },
    reviewModal: {
      rateVisit: 'Rate your visit',
      yourRating: 'Your Rating',
      poor: 'Poor',
      fair: 'Fair',
      good: 'Good',
      veryGood: 'Very Good',
      excellent: 'Excellent',
      comment: 'Comment',
      optional: 'optional',
      shareExperience: 'Share your experience with this doctor...',
      cancel: 'Cancel',
      submitReview: 'Submit Review',
      submitting: 'Submitting…',
      selectRating: 'Please select a rating',
      selectRatingText: 'Choose between 1 and 5 stars before submitting.',
      reviewSubmitted: 'Review submitted!',
      thankFeedback: 'Thank you for your feedback.',
      submissionFailed: 'Submission failed',
      failedSubmit: 'Failed to submit review. Please try again.',
    },
    doctorReviews: {
      title: 'Patient Reviews',
      noReviews: 'No reviews yet for this doctor.',
      loading: 'Loading reviews…',
      anonymous: 'Anonymous',
    },
    patientDashboard: {
      patientCenter: 'Patient Center',
      bookManage: 'Book appointments and manage your health records.',
      bookAppointment: 'Book Appointment',
      myBookings: 'My Bookings',
      welcomeBack: 'Welcome back',
      searchDoctor: 'Search doctor by name...',
      allSpecialties: 'All Specialties',
      noDoctors: 'No doctors found matching your search.',
      selectDate: 'Select a date',
      noDates: 'No available dates.',
      availableTimes: 'Available times',
      noSlots: 'No slots available',
      slotsAvailable: 'slot(s) available',
      book: 'Book',
      viewProfileReviews: 'View profile & reviews',
      perSession: 'per session',
      total: 'total',
      noBookings: "You haven't booked any appointments yet.",
      yourHistory: 'Your booking history',
      viewRx: 'View Rx',
      noPrescription: 'No prescription',
      rate: 'Rate',
      reviewed: 'Reviewed',
      cancel: 'Cancel',
      medicalPrescription: 'Medical Prescription',
      doctor: 'Doctor',
      date: 'Date',
      prescription: 'Prescription',
      diagnosis: 'Diagnosis',
      close: 'Close',
      consultationFee: 'Consultation Fee',
      contact: 'Contact',
      clinicAddress: '📍 Clinic Address',
      biography: '📋 Biography',
      noBiography: 'No biography provided by the doctor.',
      egpSession: 'EGP / session',
    },
    doctorDashboard: {
      clinicalOps: 'Clinical Operations',
      manageSchedule: 'Manage your schedule, appointments, and patient records.',
      syncWorkspace: '↻ Sync Workspace',
      syncing: 'Syncing…',
      appointments: 'Appointments',
      reviews: 'Reviews',
      schedule: 'Schedule',
      caseArchive: 'Case Archive',
      todaysAppointments: "Today's Appointments",
      awaitingApproval: 'Awaiting Approval',
      confirmedToday: 'Confirmed Today',
      accept: 'Accept',
      decline: 'Decline',
      complete: 'Complete',
      cancel: 'Cancel',
      noAppointmentsDay: 'No appointments scheduled for this day.',
      configureShift: 'Configure Shift',
      date: 'Date',
      startTime: 'Start Time',
      workingHours: 'Working Hours',
      selectHours: 'Select hours',
      hour: 'Hour',
      hours: 'Hours',
      slotDuration: 'Slot Duration',
      generateSlots: 'Generate Slots',
      noSlotsCreated: 'No slots created yet. Use the form to generate your first shift.',
      booked: 'booked',
      available: 'available',
      noSlotsDay: 'No slots for this day.',
      remove: 'Remove',
      patientReviews: 'Patient Reviews',
      patientRecords: 'Patient Records',
      searchPatient: 'Search by patient name...',
      patient: 'Patient',
      sessionDate: 'Session Date',
      diagnosis: 'Diagnosis',
      records: 'Records',
      noCompleted: 'No completed sessions found.',
      viewRecord: 'View Record',
      completeSession: 'Complete Session',
      enterFindings: 'Enter clinical findings...',
      listMeds: 'List medications and dosages...',
      doctorNotes: 'Doctor Notes',
      internalNotes: 'Internal notes for follow-up...',
      saveRecord: 'Save Record',
      consultationRecord: 'Consultation Record',
      noDiagnosis: 'No diagnosis recorded.',
      noPrescription: 'No prescription recorded.',
      minutes15: '15 Minutes',
      minutes30: '30 Minutes',
      minutes45: '45 Minutes',
      minutes60: '60 Minutes',
      today: 'Today',
    },
  },
  ar: {
    direction: 'rtl',
    nav: {
      brand: 'CarePulse',
      panel: 'لوحة',
      hello: 'أهلاً',
      profile: 'الملف الشخصي',
      logout: 'تسجيل الخروج',
      changeLanguage: 'English',
      languageLabel: 'اللغة',
    },
    common: {
      loading: 'جاري تحميل CarePulse...',
      unknown: 'غير معروف',
      yes: 'نعم',
      no: 'لا',
      cancel: 'إلغاء',
      save: 'حفظ',
      close: 'إغلاق',
      na: 'غير متاح',
      anonymous: 'مجهول',
      today: 'اليوم',
    },
    login: {
      title: 'مرحباً بعودتك',
      subtitle: 'الرجاء إدخال بيانات الدخول الخاصة بك',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      signIn: 'تسجيل الدخول',
      noAccount: 'لا تملك حساباً؟',
      createAccount: 'إنشاء حساب',
      portalTitle: 'بوابة CarePulse',
      medicalPortal: 'بوابة طبية',
      empowering: 'تمكين فرق الرعاية الصحية والتنسيق بين المرضى من خلال رؤى طبية متقدمة في الوقت الفعلي.',
      or: 'أو',
      patient: 'مريض',
      doctor: 'طبيب',
      googleFailed: 'فشل تسجيل الدخول عبر Google',
      toast: {
        invalidEmail: 'الرجاء إدخال بريد إلكتروني صالح.',
        invalidPassword: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
        success: 'تم تسجيل الدخول بنجاح',
        invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة!',
        failed: 'فشل تسجيل الدخول. حاول مرة أخرى.',
      },
    },
    register: {
      title: 'إنشاء حساب',
      subtitle: 'ابدأ بتعبئة معلومات التسجيل الخاصة بك',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      roleLabel: 'نوع الحساب',
      patient: 'مريض',
      doctor: 'طبيب',
      signUp: 'إنشاء حساب',
      existingAccount: 'هل لديك حساب بالفعل؟',
      signIn: 'تسجيل الدخول',
      toast: {
        invalidName: 'الرجاء إدخال اسم كامل صالح (3 أحرف على الأقل).',
        invalidEmail: 'الرجاء إدخال بريد إلكتروني صالح.',
        invalidPassword: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
        passwordMismatch: 'كلمات المرور غير متطابقة!',
        emailInUse: 'هذا البريد الإلكتروني مستخدم بالفعل!',
        successTitle: 'مرحباً بك في CarePulse!',
        successText: 'تم إنشاء حسابك بنجاح.',
        failed: 'فشل التسجيل. حاول مرة أخرى.',
      },
    },
    landing: {
      badge: 'بوابة موثوقة لحجز المواعيد الطبية',
      headline: 'CarePulse',
      subtitle:
        'احجز المواعيد، واطلع على تفاصيل الأطباء، وأدر الوصفات الطبية، وادفع رسوم الزيارة من مساحة صحية واحدة ومنظمة.',
      makeAppointment: 'حجز موعد',
      createAccount: 'إنشاء حساب',
      statsTitle: 'اليوم في CarePulse',
      stats: {
        doctors: 'الأطباء',
        specialties: 'التخصصات',
        patientVisits: 'زيارات المرضى',
      },
      features: {
        findDoctor: {
          title: 'اعثر على الطبيب المناسب',
          text: 'تصفح التخصصات وملفات الأطباء والملاحظات الطبية والمواعيد المتاحة.',
        },
        bookFast: {
          title: 'احجز خلال دقائق',
          text: 'اختر اليوم والوقت، ثم تابع حالة الطلب من لوحة المريض الخاصة بك.',
        },
        payments: {
          title: 'مدفوعات بسيطة',
          text: 'يمكن للمرضى دفع رسوم المواعيد من سجل حجوزاتهم.',
        },
      },
      footer: {
        text: 'يربط CarePulse المرضى والأطباء والمواعيد في بوابة طبية موثوقة واحدة.',
        copyright: '© 2026 CarePulse. جميع الحقوق محفوظة.',
      },
    },
    profile: {
      title: 'إعدادات ملفي الشخصي',
      accountType: 'نوع الحساب',
      specialty: 'التخصص الطبي',
      bio: 'نبذة احترافية',
      saveProfile: 'حفظ الملف الشخصي',
      savingChanges: 'جارٍ حفظ التغييرات...',
      emailHelp: 'لا يمكن تغيير البريد الإلكتروني',
      nameRequired: 'لا يمكن ترك حقل الاسم فارغاً!',
      updated: 'تم تحديث الملف!',
      updatedText: 'تم حفظ إعداداتك الشخصية بنجاح.',
      failedLoad: 'فشل في تحميل بيانات الملف الشخصي.',
      failedSave: 'فشل في تحديث الملف الشخصي.',
      back: 'رجوع',
      adminSettings: 'إعدادات المسؤول',
      editProfile: 'تعديل الملف الشخصي',
      username: 'اسم المستخدم',
      emailLabel: 'البريد الإلكتروني',
      firstName: 'الاسم الأول',
      lastName: 'الاسم الأخير',
      male: 'ذكر',
      female: 'أنثى',
      bloodType: 'فصيلة الدم',
      address: 'العنوان',
      fee: 'الرسوم',
      clinicAddress: 'عنوان العيادة',
      saving: 'جارٍ الحفظ...',
      saveChanges: 'حفظ التغييرات',
      profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
      profileFailed: 'فشل تحديث الملف الشخصي.',
      changePicture: 'تغيير الصورة الشخصية',
      uploading: 'جارٍ الرفع...',
      pictureUploaded: 'تم تحديث الصورة الشخصية!',
      pictureFailed: 'فشل رفع الصورة.',
      pictureTooLarge: 'يجب أن لا تتجاوز الصورة 5 ميجابايت.',
    },
    admin: {
      title: 'لوحة تحكم المسؤول',
      dashboard: 'لوحة تحكم المسؤول',
      tabs: ['المستخدمون', 'الأطباء', 'التخصصات', 'المواعيد', 'التحليلات'],
      doctorsManagement: 'إدارة الأطباء',
      usersOverview: 'جميع المستخدمين',
      specialtiesManagement: 'إدارة التخصصات',
      appointmentsOverview: 'نظرة عامة على المواعيد',
      configManagement: 'إعدادات النظام',
      analytics: 'تحليلات النظام',
      addSpecialty: 'إضافة تخصص',
      saveSpecialty: 'حفظ التخصص',
      specialtyName: 'التخصص',
      specialtyDescription: 'الوصف',
      noSpecialties: 'لا توجد تخصصات حتى الآن.',
      saveConfig: 'حفظ الإعداد',
      addConfig: 'إضافة إعداد',
      noConfigs: 'لا توجد إعدادات نظام حتى الآن.',
      refresh: 'تحديث',
      refreshing: 'جارٍ التحديث...',
      noAppointments: 'لا توجد مواعيد.',
      noUsers: 'لا توجد أطباء أو مرضى.',
      noDoctors: 'لا توجد سجلات لأطباء.',
      noDetails: '—',
      deleteSpecialtyConfirm: 'حذف التخصص؟',
      deleteSpecialtyText: 'لا يمكن التراجع عن هذا الإجراء.',
      deleteConfigConfirm: 'حذف الإعداد؟',
      deleteConfigText: '',
      deleted: 'تم الحذف',
      created: 'تم الإنشاء',
      updated: 'تم التحديث',
      unable: 'لا يمكن',
      specialtyNameRequired: 'اسم التخصص مطلوب.',
      configKeyValueRequired: 'مفتاح الإعداد والقيمة مطلوبان.',
      doctorUpdateFailed: 'فشل تحديث طبيب',
      userStatusChangeFailed: 'لا يمكن تغيير الحالة',
      specialtyAddFailed: 'لا يمكن إضافة التخصص',
      specialtyUpdateFailed: 'تعذر تحديث التخصص',
      specialtyDeleteFailed: 'لا يمكن حذف التخصص',
      configSaveFailed: 'لا يمكن حفظ الإعداد',
      configUpdateFailed: 'لا يمكن تحديث الإعداد',
      configDeleteFailed: 'لا يمكن حذف الإعداد',
      panel: {
        overviewCards: {
          users: 'المستخدمون',
          doctors: 'الأطباء',
          pendingApprovals: 'في انتظار الموافقة',
          appointments: 'المواعيد',
        },
        usersPanel: {
          title: 'جميع المستخدمين المسجلين',
          name: 'الاسم',
          email: 'البريد الإلكتروني',
          role: 'الدور',
          status: 'الحالة',
          actions: 'إجراءات',
          approve: 'موافقة',
          block: 'حظر',
          rowsPerPage: 'صفوف لكل صفحة',
          prev: 'السابق',
          next: 'التالي',
        },
        doctorsPanel: {
          noDoctors: 'لم يتم العثور على أطباء.',
          approved: 'موافق عليه',
          pending: 'قيد الانتظار',
          generalPractitioner: 'طبيب عام',
          noAddress: 'عنوان العيادة غير مدرج',
          bookAppointment: 'حجز موعد',
          approveActivate: 'موافقة وتفعيل الطبيب',
          showing: 'عرض',
          to: 'إلى',
          of: 'من',
          doctors: 'أطباء',
          prev: 'السابق',
          next: 'التالي',
        },
        specialtiesPanel: {
          title: 'إدارة التخصصات الطبية',
          name: 'اسم التخصص',
          save: 'حفظ التخصص',
          add: 'إضافة تخصص',
          cancel: 'إلغاء',
          noSpecialties: 'لا توجد تخصصات حتى الآن.',
          edit: 'تعديل التخصص',
          delete: 'حذف التخصص',
        },
        appointmentsPanel: {
          title: 'سجل نظرة عامة على المواعيد',
          refreshLogs: 'تحديث السجلات',
          refreshing: 'جارٍ التحديث...',
          patient: 'المريض',
          doctor: 'الطبيب',
          dateSlot: 'التاريخ / الفترة',
          status: 'الحالة',
          payment: 'الدفع',
          notes: 'ملاحظات',
          noAppointments: 'لا توجد مواعيد.',
          unknown: 'غير معروف',
          rowsPerPage: 'صفوف لكل صفحة',
          prev: 'السابق',
          next: 'التالي',
          paid: 'مدفوع',
          unpaid: 'غير مدفوع',
        },
        analyticsPanel: {
          title: 'محرك تحليلات النظام',
          appointmentChart: 'رسم بياني لحالة المواعيد',
          userChart: 'توزيع حالة المستخدمين',
          specialtyChart: 'ملخص الأطباء حسب التخصص',
          noSpecialtyData: 'لا توجد بيانات متاحة للتخصصات.',
        },
        configPanel: {
          title: 'إعدادات تكوين النظام',
          configKey: 'مفتاح الإعداد',
          configValue: 'قيمة الإعداد',
          save: 'حفظ الإعداد',
          add: 'إضافة إعداد',
          cancel: 'إلغاء',
          noConfigs: 'لا توجد إعدادات نظام حتى الآن.',
        },
      },
    },
    doctor: {
      title: 'لوحة الطبيب',
      tabs: ['مواعيد المرضى', 'إدارة الجدول', 'سجل المرضى'],
      currentBookings: 'الحجوزات الحالية والمعلقة',
      patientName: 'اسم المريض',
      dayTime: 'اليوم والوقت',
      status: 'الحالة',
      actions: 'إجراءات',
      noAppointments: 'لا توجد مواعيد نشطة.',
      approve: 'قبول',
      cancel: 'إلغاء',
      completePrescribe: 'إكمال ووصف',
      visitCompleted: 'تمت الزيارة!',
      recordUpdated: 'تم تحديث سجل المريض.',
      fillFields: 'الرجاء تعبئة الحقول المطلوبة.',
      failedSaveRecord: 'فشل حفظ السجل.',
      manageShift: 'إعداد الدوام',
      selectDay: 'اختر اليوم',
      totalHours: 'ساعات العمل',
      slotDuration: 'مدة الفتحة',
      generateSlots: 'إنشاء الفترات',
      noSlots: 'لا توجد فترات مجدولة بعد.',
      weeklySchedule: 'جدولك الأسبوعي (مجمّع حسب اليوم)',
      recordsHistory: 'سجل المرضى الطبي',
      searchPatient: 'ابحث باسم المريض...',
      noMatchingRecords: 'لا توجد سجلات مطابقة.',
      medicalRecord: 'سجل المريض الطبي',
      diagnosis: 'التشخيص',
      prescriptionNotes: 'الوصفة والتعليمات',
      saveComplete: 'حفظ وإكمال الزيارة',
      closeRecord: 'إغلاق السجل',
      archivedPrescription: 'الوصفة المؤرشفة',
      prescription: 'الوصفة',
      dateOfVisit: 'تاريخ الزيارة',
      noDoctorRecords: 'لا توجد أيام عمل مجدولة بعد.',
      chooseDay: '1. اختر اليوم:',
      availableTimes: '2. الأوقات المتاحة:',
      selectDayToView: 'اختر يوماً لعرض الفترات.',
      bookingConfirmationTitle: 'تأكيد الحجز',
      bookingConfirmationText: 'احجز مع د. {doctor} في {day} [{time}]؟',
      confirmBookBtn: 'نعم، احجز!',
      cancelBookBtn: 'إلغاء',
      bookSuccess: 'تم حجز الموعد بنجاح.',
      bookingFailed: 'فشل الحجز.',
      doctorName: 'اسم الطبيب',
    },
    patient: {
      title: 'مركز المريض',
      subtitle: 'حافظ على صحتك! 🛡️',
      tabs: ['حجز موعد', 'حجوزاتي والسجلات'],
      availableDoctors: 'الأطباء والمتخصصون المتاحون',
      noDoctors: 'لا يوجد أطباء مسجلون حالياً.',
      chooseDay: 'اختر اليوم:',
      availableTimes: 'الأوقات المتاحة:',
      selectDay: 'اختر يوماً لعرض الفترات.',
      bookAppointment: 'حجز موعد',
      yourHistory: 'سجل حجوزاتك',
      doctorName: 'اسم الطبيب',
      medicalPrescription: 'الوصفة الطبية',
      appointmentAvailableAfter: 'متاح بعد الزيارة',
      appointmentBooked: 'تم الحجز!',
      close: 'إغلاق',
      officialPrescription: 'الوصفة الطبية الرسمية 🩺',
      diagnosisLabel: 'التشخيص:',
      prescriptionLabel: 'الوصفة والتعليمات:',
      searchPlaceholder: 'ابحث باسم الطبيب...',
      specialtyFilter: 'تصفية حسب التخصص',
      allSpecialties: 'جميع التخصصات',
      specialist: 'أخصائي',
    },
    appointmentDetail: {
      title: 'تفاصيل الموعد',
      patient: 'المريض',
      doctor: 'الطبيب',
      dayTime: 'اليوم / الوقت',
      status: 'الحالة',
      loading: 'جاري التحميل...',
      notFound: 'لم يتم العثور على الموعد.',
      approve: 'قبول',
      rejectCancel: 'رفض / إلغاء',
      cancelAppointment: 'إلغاء الموعد',
      completeVisit: 'إكمال الزيارة',
      diagnosis: 'التشخيص',
      prescription: 'الوصفة',
      saveComplete: 'حفظ وإكمال',
      fillDiagnosisPrescription: 'الرجاء إدخال التشخيص والوصفة',
      approved: 'تمت الموافقة',
      cancelled: 'تم الإلغاء',
      completed: 'تم الإكمال',
      failed: 'فشل',
      notificationApprovedTitle: 'تمت الموافقة على الموعد',
      notificationApprovedBody: 'تمت الموافقة على موعدك.',
      notificationCancelledTitle: 'تم إلغاء الموعد',
      notificationCancelledBody: 'تم إلغاء موعدك.',
      notificationCompletedTitle: 'تمت الزيارة',
      notificationCompletedBody: 'تمت زيارتك والوصفة متاحة الآن.',
    },
    overviewCards: {
      users: 'المستخدمون',
      doctors: 'الأطباء',
      pendingApprovals: 'في انتظار الموافقة',
      appointments: 'المواعيد',
    },
    statuses: {
      approved: 'موافق عليه',
      pending: 'قيد الانتظار',
      blocked: 'محظور',
      cancelled: 'ملغي',
      completed: 'مكتمل',
      unknown: 'غير معروف',
    },
    roles: {
      doctor: 'طبيب',
      patient: 'مريض',
      admin: 'مدير',
      unknown: 'غير معروف',
    },
    days: {
      Monday: 'الاثنين',
      Tuesday: 'الثلاثاء',
      Wednesday: 'الأربعاء',
      Thursday: 'الخميس',
      Friday: 'الجمعة',
      Saturday: 'السبت',
      Sunday: 'الأحد',
    },
    notifications: {
      newRequestTitle: 'طلب موعد جديد',
      newRequestBody: 'المريض {patient} طلب موعدًا يوم {day} الساعة {time}',
      bookingCreatedTitle: 'تم إنشاء الحجز',
      bookingCreatedBody: 'حجزك مع د. {doctor} يوم {day} الساعة {time} قيد الانتظار.',
      bookedTitle: 'تم الحجز!',
      bookedSuccess: 'تم تأمين الموعد بنجاح.',
      bookingFailed: 'فشل الحجز.',
      title: 'الإشعارات',
      noNotifications: 'لا توجد إشعارات بعد.',
      unread: 'غير مقروء',
      deleteConfirm: 'حذف الإشعار؟',
      delete: 'حذف',
      deleted: 'تم الحذف',
      failedDelete: 'فشل الحذف',
      open: 'فتح',
      markAsRead: 'تحديد كمقروء',
    },
    home: {
      welcome: 'مرحباً',
      manageDoctor: 'أدر جدولك وطلبات المرضى والمراجعات من مكان واحد.',
      findCare: 'ابحث عن رعاية صحية واحجز المواعيد وراسل مقدمي خدماتك بسرعة.',
      overviewSystem: 'نظرة عامة على صحة النظام والمهام المعلقة.',
      openDashboard: 'فتح لوحة التحكم',
      viewNotifications: 'عرض الإشعارات',
      keyFeatures: 'الميزات الرئيسية',
      easyBooking: 'حجز سهل',
      easyBookingDesc: 'حدد المواعيد بنقرات قليلة واحصل على تذكيرات.',
      trustedCare: 'رعاية موثوقة',
      trustedCareDesc: 'متخصصون موثوقون وسجلات طبية آمنة.',
      fastMessaging: 'رسائل سريعة',
      fastMessagingDesc: 'مراسلة آنة مباشرة مع فريق الرعاية الخاص بك.',
      whatPeopleSay: 'ماذا يقول الناس',
      profile: 'الملف الشخصي',
      appointments: 'المواعيد',
      recentNotifications: 'إشعارات حديثة',
      noRecentNotifications: 'لا توجد إشعارات حديثة.',
      new: 'جديد',
      quickLinks: 'روابط سريعة',
      myVisits: 'زياراتي',
      allNotifications: 'جميع الإشعارات',
      support: 'الدعم',
    },
    verify: {
      title: 'تفعيل الحساب',
      enterCode: 'أدخل الكود المرسل إلى',
      yourEmail: 'بريدك الإلكتروني',
      code: 'كود التحقق',
      activating: 'جارٍ التحقق...',
      activateAccount: 'تفعيل الحساب',
      invalidInput: 'إدخال غير صالح',
      enterCodeMessage: 'الرجاء إدخال الكود المكون من 6 أرقام.',
      success: 'تم التحقق!',
      failed: 'فشل التحقق',
      incorrectCode: 'الكود غير صحيح أو منتهي الصلاحية.',
    },
    reviewModal: {
      rateVisit: 'قيّم زيارتك',
      yourRating: 'تقييمك',
      poor: 'ضعيف',
      fair: 'مقبول',
      good: 'جيد',
      veryGood: 'جيد جداً',
      excellent: 'ممتاز',
      comment: 'تعليق',
      optional: 'اختياري',
      shareExperience: 'شارك تجربتك مع هذا الطبيب...',
      cancel: 'إلغاء',
      submitReview: 'إرسال المراجعة',
      submitting: 'جارٍ الإرسال...',
      selectRating: 'الرجاء اختيار تقييم',
      selectRatingText: 'اختر بين 1 إلى 5 نجوم قبل الإرسال.',
      reviewSubmitted: 'تم إرسال المراجعة!',
      thankFeedback: 'شكراً لملاحظاتك.',
      submissionFailed: 'فشل الإرسال',
      failedSubmit: 'فشل إرسال المراجعة. حاول مرة أخرى.',
    },
    doctorReviews: {
      title: 'مراجعات المرضى',
      noReviews: 'لا توجد مراجعات لهذا الطبيب بعد.',
      loading: 'جارٍ تحميل المراجعات...',
      anonymous: 'مجهول',
    },
    patientDashboard: {
      patientCenter: 'مركز المريض',
      bookManage: 'احجز المواعيد وأدر سجلات صحتك.',
      bookAppointment: 'حجز موعد',
      myBookings: 'حجوزاتي',
      welcomeBack: 'مرحباً بعودتك',
      searchDoctor: 'ابحث عن طبيب بالاسم...',
      allSpecialties: 'جميع التخصصات',
      noDoctors: 'لم يتم العثور على أطباء مطابقين.',
      selectDate: 'اختر تاريخاً',
      noDates: 'لا توجد تواريخ متاحة.',
      availableTimes: 'الأوقات المتاحة',
      noSlots: 'لا توجد فترات متاحة',
      slotsAvailable: 'فترة متاحة',
      book: 'احجز',
      viewProfileReviews: 'عرض الملف والمراجعات',
      perSession: 'لكل جلسة',
      total: 'المجموع',
      noBookings: 'لم تحجز أي مواعيد بعد.',
      yourHistory: 'سجل حجوزاتك',
      viewRx: 'عرض الوصفة',
      noPrescription: 'لا توجد وصفة',
      rate: 'تقييم',
      reviewed: 'تمت المراجعة',
      cancel: 'إلغاء',
      medicalPrescription: 'الوصفة الطبية',
      doctor: 'الطبيب',
      date: 'التاريخ',
      prescription: 'الوصفة',
      diagnosis: 'التشخيص',
      close: 'إغلاق',
      consultationFee: 'رسوم الاستشارة',
      contact: 'التواصل',
      clinicAddress: '📍 عنوان العيادة',
      biography: '📋 السيرة الذاتية',
      noBiography: 'لم يقدم الطبيب سيرة ذاتية.',
      egpSession: 'جنيه / جلسة',
    },
    doctorDashboard: {
      clinicalOps: 'العمليات السريرية',
      manageSchedule: 'أدر جدولك ومواعيدك وسجلات المرضى.',
      syncWorkspace: 'مزامنة مساحة العمل',
      syncing: 'جارٍ المزامنة...',
      appointments: 'المواعيد',
      reviews: 'المراجعات',
      schedule: 'الجدول',
      caseArchive: 'أرشيف الحالات',
      todaysAppointments: 'مواعيد اليوم',
      awaitingApproval: 'في انتظار الموافقة',
      confirmedToday: 'مؤكد اليوم',
      accept: 'قبول',
      decline: 'رفض',
      complete: 'إكمال',
      cancel: 'إلغاء',
      noAppointmentsDay: 'لا توجد مواعيد مجدولة لهذا اليوم.',
      configureShift: 'إعداد الدوام',
      date: 'التاريخ',
      startTime: 'وقت البداية',
      workingHours: 'ساعات العمل',
      selectHours: 'اختر الساعات',
      hour: 'ساعة',
      hours: 'ساعات',
      slotDuration: 'مدة الفترة',
      generateSlots: 'إنشاء الفترات',
      noSlotsCreated: 'لم يتم إنشاء فترات بعد. استخدم النموذج لإنشاء أول دوام.',
      booked: 'محجوز',
      available: 'متاح',
      noSlotsDay: 'لا توجد فترات لهذا اليوم.',
      remove: 'إزالة',
      patientReviews: 'مراجعات المرضى',
      patientRecords: 'سجلات المرضى',
      searchPatient: 'بحث باسم المريض...',
      patient: 'المريض',
      sessionDate: 'تاريخ الجلسة',
      diagnosis: 'التشخيص',
      records: 'السجلات',
      noCompleted: 'لم يتم العثور على جلسات مكتملة.',
      viewRecord: 'عرض السجل',
      completeSession: 'إكمال الجلسة',
      enterFindings: 'أدخل النتائج السريرية...',
      listMeds: 'اذكر الأدوية والجرعات...',
      doctorNotes: 'ملاحظات الطبيب',
      internalNotes: 'ملاحظات داخلية للمتابعة...',
      saveRecord: 'حفظ السجل',
      consultationRecord: 'سجل الاستشارة',
      noDiagnosis: 'لم يتم تسجيل تشخيص.',
      noPrescription: 'لم يتم تسجيل وصفة.',
      minutes15: '15 دقيقة',
      minutes30: '30 دقيقة',
      minutes45: '45 دقيقة',
      minutes60: '60 دقيقة',
      today: 'اليوم',
    },
  },
};

const LanguageContext = createContext({});

const getNestedValue = (obj, key) => {
  return key.split('.').reduce((current, part) => {
    if (current == null) return undefined;
    return current[part];
  }, obj);
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('appLanguage') || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('appLanguage', language);
      document.documentElement.lang = language;
      const dir = translations[language]?.direction || 'ltr';
      document.documentElement.dir = dir;
      document.body.dir = dir;
    }
  }, [language]);

  const t = useCallback(
    (key, fallback = '') => {
      const value = getNestedValue(translations[language], key);
      return value ?? fallback ?? key;
    },
    [language]
  );

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => (prev === 'en' ? 'ar' : 'en'));
  }, []);

  const value = useMemo(
    () => ({ language, setLanguage, toggleLanguage, t }),
    [language, setLanguage, toggleLanguage, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
