import { createContext, useContext, useEffect, useMemo, useState, useCallback } from 'react';

const translations = {
  en: {
    direction: 'ltr',
    nav: {
      brand: 'CarePulse',
      panel: 'Panel',
      hello: 'Hello',
      profile: 'Profile',
      logout: 'Logout',
      changeLanguage: 'العربية',
      languageLabel: 'Language',
    },
    common: {
      loading: 'Loading CarePulse...',
      unknown: 'Unknown',
      yes: 'Yes',
      no: 'No',
      cancel: 'Cancel',
      save: 'Save',
      close: 'Close',
    },
    login: {
      title: 'Welcome Back',
      subtitle: 'Please enter your medical portal credentials',
      email: 'Email Address',
      password: 'Password',
      signIn: 'Sign In',
      noAccount: "Don't have an account?",
      createAccount: 'Create Portal Account',
      portalTitle: 'CarePulse Portal',
      toast: {
        invalidEmail: 'Please enter a valid email address.',
        invalidPassword: 'Password must be at least 6 characters.',
        success: 'Signed in successfully',
        invalidCredentials: 'Invalid email or password!',
        failed: 'Failed to log in. Please try again.',
      },
    },
    register: {
      title: 'Create Account',
      subtitle: 'Get started by filling your registration info',
      fullName: 'Full Name',
      email: 'Email Address',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      roleLabel: 'Portal Access Role',
      patient: 'Patient',
      doctor: 'Doctor',
      signUp: 'Sign Up',
      existingAccount: 'Already have an account?',
      signIn: 'Sign In',
      toast: {
        invalidName: 'Please enter a valid full name (at least 3 characters).',
        invalidEmail: 'Please enter a valid email address.',
        invalidPassword: 'Password must be at least 6 characters long.',
        passwordMismatch: 'Passwords do not match!',
        emailInUse: 'This email is already in use!',
        successTitle: 'Welcome to CarePulse!',
        successText: 'Your account has been created successfully.',
        failed: 'Registration failed. Try again.',
      },
    },
    profile: {
      title: 'My Profile Settings',
      accountType: 'Account Type',
      specialty: 'Medical Specialty',
      bio: 'Professional Bio',
      saveProfile: 'Save Profile',
      savingChanges: 'Saving Changes...',
      emailHelp: 'Email account cannot be changed',
      nameRequired: 'Name field cannot be empty!',
      updated: 'Profile Updated!',
      updatedText: 'Your personal settings have been saved successfully.',
      failedLoad: 'Failed to load profile data.',
      failedSave: 'Failed to update profile.',
    },
    admin: {
      title: 'Admin Control Center',
      dashboard: 'Admin Control Center',
      tabs: ['Users', 'Doctors', 'Specialties', 'Appointments', 'Config', 'Analytics'],
      doctorsManagement: 'Doctors Management',
      usersOverview: 'All Users',
      specialtiesManagement: 'Specialties Management',
      appointmentsOverview: 'Appointments Overview',
      configManagement: 'System Configuration',
      analytics: 'System Analytics',
      addSpecialty: 'Add Specialty',
      saveSpecialty: 'Save Specialty',
      specialtyName: 'Specialty',
      specialtyDescription: 'Description',
      noSpecialties: 'No specialties configured yet.',
      saveConfig: 'Save Config',
      addConfig: 'Add Config',
      noConfigs: 'No system configuration entries yet.',
      refresh: 'Refresh',
      refreshing: 'Refreshing...',
      noAppointments: 'No appointments found.',
      noUsers: 'No doctors or patients available.',
      noDoctors: 'No doctor records found.',
      noDetails: '—',
      deleteSpecialtyConfirm: 'Delete specialty?',
      deleteSpecialtyText: 'This action cannot be undone.',
      deleteConfigConfirm: 'Delete configuration?',
      deleteConfigText: '',
      deleted: 'Deleted',
      created: 'Created',
      updated: 'Updated',
      unable: 'Unable to',
      specialtyNameRequired: 'Specialty name is required.',
      configKeyValueRequired: 'Config key and value are required.',
      doctorUpdateFailed: 'Failed to update doctor',
      userStatusChangeFailed: 'Unable to change status',
      specialtyAddFailed: 'Unable to add specialty',
      specialtyUpdateFailed: 'Could not update specialty',
      specialtyDeleteFailed: 'Unable to delete specialty',
      configSaveFailed: 'Unable to save config',
      configUpdateFailed: 'Unable to update config',
      configDeleteFailed: 'Unable to delete config',
    },
    doctor: {
      title: 'Doctor Workspace',
      tabs: ['Patient Appointments', 'Manage Work Schedule', 'Patients Medical History'],
      currentBookings: 'Current & Pending Bookings',
      patientName: 'Patient Name',
      dayTime: 'Day & Time',
      status: 'Status',
      actions: 'Actions',
      noAppointments: 'No active appointments found.',
      approve: 'Approve',
      cancel: 'Cancel',
      completePrescribe: 'Complete & Prescribe',
      visitCompleted: 'Visit Completed!',
      recordUpdated: 'Patient record updated.',
      fillFields: 'Please fill in both fields.',
      failedSaveRecord: 'Failed to save record.',
      manageShift: 'Setup Working Shift',
      selectDay: 'Select Day',
      totalHours: 'Total Work Hours',
      slotDuration: 'Slot Duration',
      generateSlots: 'Generate Shift Slots',
      noSlots: 'No slots active on your schedule yet.',
      weeklySchedule: 'Your Weekly Schedule (Grouped by Day)',
      recordsHistory: 'Patients Medical Records History',
      searchPatient: 'Search Patient Name...',
      noMatchingRecords: 'No matching records found in patient history.',
      medicalRecord: 'Patient Medical Record',
      diagnosis: 'Diagnosis',
      prescriptionNotes: 'Prescription & Notes',
      saveComplete: 'Save & Complete Visit',
      closeRecord: 'Close Record',
      archivedPrescription: 'Archived Prescription',
      prescription: 'Prescription',
      dateOfVisit: 'Date of Visit',
      noDoctorRecords: 'No working days scheduled yet.',
      chooseDay: '1. Choose Day:',
      availableTimes: '2. Available Times:',
      selectDayToView: 'Select a day to view slots.',
      bookingConfirmationTitle: 'Confirm Booking',
      bookingConfirmationText: 'Book with Dr. {doctor} on {day} [{time}]?',
      bookSuccess: 'Appointment secured successfully.',
      bookingFailed: 'Booking failed.',
      doctorName: 'Doctor Name',
    },
    patient: {
      title: 'Patient Center',
      subtitle: 'Stay healthy! 🛡️',
      tabs: ['Book An Appointment', 'My Bookings & Records'],
      availableDoctors: 'Available Doctors & Specialists',
      noDoctors: 'No registered doctors available right now.',
      chooseDay: 'Choose Day:',
      availableTimes: 'Available Times:',
      selectDay: 'Select a day to view slots.',
      bookAppointment: 'Book An Appointment',
      yourHistory: 'Your Booking History',
      doctorName: 'Doctor Name',
      medicalPrescription: 'Medical Prescription',
      appointmentAvailableAfter: 'Available after visit',
      appointmentBooked: 'Booked!',
      close: 'Close',
      officialPrescription: 'Official Medical Prescription 🩺',
      diagnosisLabel: 'Diagnosis (التشخيص):',
      prescriptionLabel: 'Prescription & Notes (العلاج والتعليمات):',
    },
    overviewCards: {
      users: 'Users',
      doctors: 'Doctors',
      pendingApprovals: 'Pending Approvals',
      appointments: 'Appointments',
    },
    statuses: {
      approved: 'Approved',
      pending: 'Pending',
      blocked: 'Blocked',
      cancelled: 'Cancelled',
      completed: 'Completed',
      unknown: 'Unknown',
    },
    roles: {
      doctor: 'Doctor',
      patient: 'Patient',
      admin: 'Admin',
      unknown: 'Unknown',
    },
  },
  ar: {
    direction: 'rtl',
    nav: {
      brand: 'CarePulse',
      panel: 'لوحة',
      hello: 'أهلاً',
      profile: 'الملف الشخصي',
      logout: 'تسجيل الخروج',
      changeLanguage: 'English',
      languageLabel: 'اللغة',
    },
    common: {
      loading: 'جاري تحميل CarePulse...',
      unknown: 'غير معروف',
      yes: 'نعم',
      no: 'لا',
      cancel: 'إلغاء',
      save: 'حفظ',
      close: 'إغلاق',
    },
    login: {
      title: 'مرحباً بعودتك',
      subtitle: 'الرجاء إدخال بيانات الدخول الخاصة بك',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      signIn: 'تسجيل الدخول',
      noAccount: 'لا تملك حساباً؟',
      createAccount: 'إنشاء حساب',
      portalTitle: 'بوابة CarePulse',
      toast: {
        invalidEmail: 'الرجاء إدخال بريد إلكتروني صالح.',
        invalidPassword: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
        success: 'تم تسجيل الدخول بنجاح',
        invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة!',
        failed: 'فشل تسجيل الدخول. حاول مرة أخرى.',
      },
    },
    register: {
      title: 'إنشاء حساب',
      subtitle: 'ابدأ بتعبئة معلومات التسجيل الخاصة بك',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      roleLabel: 'نوع الحساب',
      patient: 'مريض',
      doctor: 'طبيب',
      signUp: 'إنشاء حساب',
      existingAccount: 'هل لديك حساب بالفعل؟',
      signIn: 'تسجيل الدخول',
      toast: {
        invalidName: 'الرجاء إدخال اسم كامل صالح (3 أحرف على الأقل).',
        invalidEmail: 'الرجاء إدخال بريد إلكتروني صالح.',
        invalidPassword: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
        passwordMismatch: 'كلمات المرور غير متطابقة!',
        emailInUse: 'هذا البريد الإلكتروني مستخدم بالفعل!',
        successTitle: 'مرحباً بك في CarePulse!',
        successText: 'تم إنشاء حسابك بنجاح.',
        failed: 'فشل التسجيل. حاول مرة أخرى.',
      },
    },
    profile: {
      title: 'إعدادات ملفي الشخصي',
      accountType: 'نوع الحساب',
      specialty: 'التخصص الطبي',
      bio: 'نبذة احترافية',
      saveProfile: 'حفظ الملف الشخصي',
      savingChanges: 'جارٍ حفظ التغييرات...',
      emailHelp: 'لا يمكن تغيير البريد الإلكتروني',
      nameRequired: 'لا يمكن ترك حقل الاسم فارغاً!',
      updated: 'تم تحديث الملف!',
      updatedText: 'تم حفظ إعداداتك الشخصية بنجاح.',
      failedLoad: 'فشل في تحميل بيانات الملف الشخصي.',
      failedSave: 'فشل في تحديث الملف الشخصي.',
    },
    admin: {
      title: 'لوحة تحكم المسؤول',
      dashboard: 'لوحة تحكم المسؤول',
      tabs: ['المستخدمون', 'الأطباء', 'التخصصات', 'المواعيد', 'الإعدادات', 'التحليلات'],
      doctorsManagement: 'إدارة الأطباء',
      usersOverview: 'جميع المستخدمين',
      specialtiesManagement: 'إدارة التخصصات',
      appointmentsOverview: 'نظرة عامة على المواعيد',
      configManagement: 'إعدادات النظام',
      analytics: 'تحليلات النظام',
      addSpecialty: 'إضافة تخصص',
      saveSpecialty: 'حفظ التخصص',
      specialtyName: 'التخصص',
      specialtyDescription: 'الوصف',
      noSpecialties: 'لا توجد تخصصات حتى الآن.',
      saveConfig: 'حفظ الإعداد',
      addConfig: 'إضافة إعداد',
      noConfigs: 'لا توجد إعدادات نظام حتى الآن.',
      refresh: 'تحديث',
      refreshing: 'جارٍ التحديث...',
      noAppointments: 'لا توجد مواعيد.',
      noUsers: 'لا توجد أطباء أو مرضى.',
      noDoctors: 'لا توجد سجلات لأطباء.',
      noDetails: '—',
      deleteSpecialtyConfirm: 'حذف التخصص؟',
      deleteSpecialtyText: 'لا يمكن التراجع عن هذا الإجراء.',
      deleteConfigConfirm: 'حذف الإعداد؟',
      deleteConfigText: '',
      deleted: 'تم الحذف',
      created: 'تم الإنشاء',
      updated: 'تم التحديث',
      unable: 'لا يمكن',
      specialtyNameRequired: 'اسم التخصص مطلوب.',
      configKeyValueRequired: 'مفتاح الإعداد والقيمة مطلوبان.',
      doctorUpdateFailed: 'فشل تحديث طبيب',
      userStatusChangeFailed: 'لا يمكن تغيير الحالة',
      specialtyAddFailed: 'لا يمكن إضافة التخصص',
      specialtyUpdateFailed: 'تعذر تحديث التخصص',
      specialtyDeleteFailed: 'لا يمكن حذف التخصص',
      configSaveFailed: 'لا يمكن حفظ الإعداد',
      configUpdateFailed: 'لا يمكن تحديث الإعداد',
      configDeleteFailed: 'لا يمكن حذف الإعداد',
    },
    doctor: {
      title: 'لوحة الطبيب',
      tabs: ['مواعيد المرضى', 'إدارة الجدول', 'سجل المرضى'],
      currentBookings: 'الحجوزات الحالية والمعلقة',
      patientName: 'اسم المريض',
      dayTime: 'اليوم والوقت',
      status: 'الحالة',
      actions: 'إجراءات',
      noAppointments: 'لا توجد مواعيد نشطة.',
      approve: 'قبول',
      cancel: 'إلغاء',
      completePrescribe: 'إكمال ووصف',
      visitCompleted: 'تمت الزيارة!',
      recordUpdated: 'تم تحديث سجل المريض.',
      fillFields: 'الرجاء تعبئة الحقول المطلوبة.',
      failedSaveRecord: 'فشل حفظ السجل.',
      manageShift: 'إعداد الدوام',
      selectDay: 'اختر اليوم',
      totalHours: 'ساعات العمل',
      slotDuration: 'مدة الفتحة',
      generateSlots: 'إنشاء الفترات',
      noSlots: 'لا توجد فترات مجدولة بعد.',
      weeklySchedule: 'جدولك الأسبوعي (مجمّع حسب اليوم)',
      recordsHistory: 'سجل المرضى الطبي',
      searchPatient: 'ابحث باسم المريض...',
      noMatchingRecords: 'لا توجد سجلات مطابقة.',
      medicalRecord: 'سجل المريض الطبي',
      diagnosis: 'التشخيص',
      prescriptionNotes: 'الوصفة والتعليمات',
      saveComplete: 'حفظ وإكمال الزيارة',
      closeRecord: 'إغلاق السجل',
      archivedPrescription: 'الوصفة المؤرشفة',
      prescription: 'الوصفة',
      dateOfVisit: 'تاريخ الزيارة',
      noDoctorRecords: 'لا توجد أيام عمل مجدولة بعد.',
      chooseDay: '1. اختر اليوم:',
      availableTimes: '2. الأوقات المتاحة:',
      selectDayToView: 'اختر يوماً لعرض الفترات.',
      bookingConfirmationTitle: 'تأكيد الحجز',
      bookingConfirmationText: 'احجز مع د. {doctor} في {day} [{time}]؟',
      bookSuccess: 'تم حجز الموعد بنجاح.',
      bookingFailed: 'فشل الحجز.',
      doctorName: 'اسم الطبيب',
    },
    patient: {
      title: 'مركز المريض',
      subtitle: 'حافظ على صحتك! 🛡️',
      tabs: ['حجز موعد', 'حجوزاتي والسجلات'],
      availableDoctors: 'الأطباء والمتخصصون المتاحون',
      noDoctors: 'لا يوجد أطباء مسجلون حالياً.',
      chooseDay: 'اختر اليوم:',
      availableTimes: 'الأوقات المتاحة:',
      selectDay: 'اختر يوماً لعرض الفترات.',
      bookAppointment: 'حجز موعد',
      yourHistory: 'سجل حجوزاتك',
      doctorName: 'اسم الطبيب',
      medicalPrescription: 'الوصفة الطبية',
      appointmentAvailableAfter: 'متاح بعد الزيارة',
      appointmentBooked: 'تم الحجز!',
      close: 'إغلاق',
      officialPrescription: 'الوصفة الطبية الرسمية 🩺',
      diagnosisLabel: 'التشخيص:',
      prescriptionLabel: 'الوصفة والتعليمات:',
    },
    overviewCards: {
      users: 'المستخدمون',
      doctors: 'الأطباء',
      pendingApprovals: 'في انتظار الموافقة',
      appointments: 'المواعيد',
    },
    statuses: {
      approved: 'موافق عليه',
      pending: 'قيد الانتظار',
      blocked: 'محظور',
      cancelled: 'ملغي',
      completed: 'مكتمل',
      unknown: 'غير معروف',
    },
    roles: {
      doctor: 'طبيب',
      patient: 'مريض',
      admin: 'مدير',
      unknown: 'غير معروف',
    },
  },
};

const LanguageContext = createContext({});

const getNestedValue = (obj, key) => {
  return key.split('.').reduce((current, part) => {
    if (current == null) return undefined;
    return current[part];
  }, obj);
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('appLanguage') || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('appLanguage', language);
      document.documentElement.lang = language;
      const dir = translations[language]?.direction || 'ltr';
      document.documentElement.dir = dir;
      document.body.dir = dir;
    }
  }, [language]);

  const t = useCallback(
    (key, fallback = '') => {
      const value = getNestedValue(translations[language], key);
      return value ?? fallback ?? key;
    },
    [language]
  );

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => (prev === 'en' ? 'ar' : 'en'));
  }, []);

  const value = useMemo(
    () => ({ language, setLanguage, toggleLanguage, t }),
    [language, setLanguage, toggleLanguage, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
